site_name: MilkCr8 CNC Wiki
theme:
  name: material
  palette:
    scheme: milk-cr8
  icon:
    logo: material/cube-outline
extra_css:
  - stylesheets/extra.css
nav:
    - Home: 'index.md'
    - About: 'about.md'
    - FAQ: 'faq.md'
    - BOM: 'bom.md'
    - Print Settings: 'printing.md'
    - Assembly: 'assembly.md'